# Generated by Django 5.2.8 on 2025-11-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('interes', models.CharField(choices=[('trazabilidad', 'Trazabilidad'), ('canchas', 'Arriendo de canchas'), ('escuelas', 'Escuelas de fútbol'), ('farmacia', 'Farmacia / retail'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('mensaje', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
